### ISSUE TITLE
No packages in Package Center for packages.jdel.org

### ISSUE THREAD

**Issue by szyb** [jdel/gosspks#3]
I look on the website packages.jdel.org and for my model  (DS718+ apollolake) there are 2 packages, however when I add the link in Package Center (DSM 6.1.6 Update 1) there are no packages from this source.

**Comment by jdel** [comment]
Thanks for reporting this, I will have a look.

**Comment by jdel** [comment]
This is fixed in v0.1.1. Can you give it another try ?

**Comment by szyb** [comment]
Yes, now it looks fine in Package Center

**Comment by CrabThug** [comment]
isn't good for me, I'm on a 718+ too

**Comment by jdel** [comment]
I have cleaned up old packages and there are no more apollolake packages left.

I don't know what you're looking for, but you can try https://mirrors.packages.jdel.org which is a mirror of a few different other packages servers around. 

Packages won't show in the UI, but will show in your Package Center.

**Comment by CrabThug** [comment]
Hi,

Ur link is dead, can u help me about my issue ?

**Comment by jdel** [comment]
The link has been fixed. Please stop using this issue, this problem is solved.
