### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by CrabThug** [jdel/gosspks#5]
Hi,

I'm locked on a http error 400

**Comment by CrabThug** [comment]
I hav always this 400 error but now I've white screen :/

**Comment by jdel** [comment]
I cannot help you with this unless you provide more details.

What are you trying to achieve ?  What are you expecting ? What are you actually getting ?

Are you running your own instance of gosspks or reporting an issue for packages.jdel.org ?

**Comment by CrabThug** [comment]
I can't link gosspks with gosspks-ui with my Synology :/

**Comment by CrabThug** [comment]
Creating gosspks ... error

ERROR: for gosspks  Cannot start service gosspks: Bind mount failed: '/root/packages' does not exists

ERROR: for gosspks  Cannot start service gosspks: Bind mount failed: '/root/packages' does not exists
ERROR: Encountered errors while bringing up the project.

**Comment by jdel** [comment]
I am willing to help you, but only if you make the effort of telling me how you are trying to set up gosspks, and possibly answer the questions above.

**Comment by CrabThug** [comment]
ho ok, i try to start gosspks with docker on my Synology.

when I try with ur docker-compose.yml with docker-compose up -d 

i hav an error who say : ERROR: for gosspks Cannot start service gosspks: Bind mount failed: '/root/packages' does not exists

**Comment by CrabThug** [comment]
I can install gosspks and gosspks-ui but I don't know how to link both :/

**Comment by jdel** [comment]
From the error message above, I am pretty sure gosspks is not running. Focus on getting gosspks to run first, once your Synology can reach gosspks, it will be easy to deploy the UI.

You need to change `$HOME/packages/` in the docker-compose file to reflect the location on disk where you are storing your packages on your Synology device.

**Comment by CrabThug** [comment]
how can I know when gosspks is running well ?

**Comment by jdel** [comment]
ok let me ask one more question. what are you hoping to do with gosspks ?

**Comment by CrabThug** [comment]
I want just stock my homemade spk

**Comment by jdel** [comment]
Ok, good answer. Then you would check if it works by adding the URL to your synology package center, or by using a utility like `curl` on linux, or simply browsing to `yourdomain.com/about` with any web browser and it should display the build information like so:

```
{
name: "gosspks",
version: "v0.1.2-1f9ebb1",
maintainer: "jdel",
license: "GNU GPL v3",
year: 2018
}
```

To achieve it, you will need basic knowledge of:
  - DNS (buying a domain name, A and CNAME records)
  - Web hosting / TCP (what's a web server, what are TCP ports)
  - Docker (running docker containers, volumes, publishing ports)

Unfortunately, this issue is not the right place for those queries.

**Comment by CrabThug** [comment]
with my browser and the url.

i hav all knowledge needed for use this I hope ^^

**Comment by CrabThug** [comment]
I tried to access with my local IP,
I know I ask him cause the  Debug mode give me an HTTP 400 error 
But my browser screen stay white. when I use only the GoSSPKS container

**Comment by CrabThug** [comment]
I'm French, if it can help u

**Comment by jdel** [comment]
have you changed `$HOME/packages/` to where your SPK are stored ?

**Comment by CrabThug** [comment]
need I to change it if I can write in ?

**Comment by jdel** [comment]
https://gitter.im/gosspks

**Comment by CrabThug** [comment]
it was a stupid problem of right,

ty for helping

**Comment by CrabThug** [comment]
i want just add one comment.
Error 400 and White screen isn't a problem cause it's just an API
but if u use a Synology like me, change the directory right on dsm BEFORE start the new container or the folder ll be clear. 
and secondary, mount the good directory, not like me ^^ : /home/user/gosspks
add this directory, better for change the config file ;) 

really nice work Jdel. last day u was perfect but I was so tired ^^
now ur application is fully functional 

see u ;)
