### ISSUE TITLE
One package moved to ignored

### ISSUE THREAD

**Issue by DigitalBox98** [jdel/gosspks#7]
When requesting package list, one package is ignored.

Packages in the $HOME/gosspks/packages/ :
- erlang_braswell-6.1_22.1-1.spk (size 57 401 760)
- icecast_braswell-6.1_2.4.4-2.spk (size 4 782 080)

Launching gosspks server : 
gosspks-linux-amd64 --port 1500 -l debug 

Retrieving packages list : 
curl -i 10.0.2.15:1500/v1/packages
=> Only Icecast is displayed
=> Erlang package is renamed to "erlang_braswell-6.1_22.1-1.spk.ignored"

Debug log : 
DEBU[19/11/14 21:16:19.109] Processing 2 files                            module=handler/v1/v1.go
DEBU[19/11/14 21:16:19.109] Started processing                            filename=erlang_braswell-6.1_22.1-1.spk module=handler/v1/v1.go size="57 MB"
DEBU[19/11/14 21:16:19.109] Started processing                            filename=icecast_braswell-6.1_2.4.4-2.spk module=handler/v1/v1.go size="4.8 MB"
DEBU[19/11/14 21:16:19.109] Finished processing                           duration=1ms filename=icecast_braswell-6.1_2.4.4-2.spk module=handler/v1/v1.go
DEBU[19/11/14 21:16:19.110] Finished processing                           duration=0s filename=erlang_braswell-6.1_22.1-1.spk module=handler/v1/v1.go
DEBU[19/11/14 21:16:19.110] Stored syno packages () in cache for 5m0s     module=handler/v1/v1.go
INFO[19/11/14 21:16:19.110] 10.0.2.15 - - [14/Nov/2019:21:16:19 +0100] "GET /v1/packages HTTP/1.1" 200 1149  module=lgr/lgr.go route=Packages template=/v1/packages

**Comment by jdel** [comment]
could you share `erlang_braswell-6.1_22.1-1.spk ` ?

**Comment by DigitalBox98** [comment]
Yes it’s downloadable on : http://digital.box.free.fr/files/erlang_braswell-6.1_22.1-1.spk

**Comment by jdel** [comment]
Your `spk` is gzipped. The Synology package specifications requires a tar archive without gzip.

I repacked it as a tar archive and it works perfectly fine.

> Your file
```
# file erlang_braswell-6.1_22.1-1.spk.ignored
erlang_braswell-6.1_22.1-1.spk.ignored: gzip compressed data, was "erlang_braswell-6.1_22.1-1.tar", last modified: Fri Oct 11 22:45:45 2019, from Unix, original size modulo 2^32 57682944
```

> After repacking
```
# file erlang_braswell-6.1_22.1-1.spk
erlang_braswell-6.1_22.1-1.spk: POSIX tar archive
```
